apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-redux-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-redux-app
  template:
    metadata:
      labels:
        app: react-redux-app
    spec:
      containers:
      - name: react-redux
        image: react-redux:1.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      restartPolicy: Always
