apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-redux-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-redux-app
  template:
    metadata:
      labels:
        app: react-redux-app
    spec:
      containers:
      - name: react-redux
        image: react-redux:1.0.0
        resources:
          limits:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: react-redux-service
spec:
  selector:
    app: react-redux-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 80
---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: myingress
#   labels:
#     name: myingress
# spec:
#   rules:
#   - host: <Host>
#     http:
#       paths:
#       - pathType: Prefix
#         path: "/"
#         backend:
#           service:
#             name: <Service>
#             port: 
#               number: 8000
